# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: credentials-sync
# data:
#   ACR_NAME: cdwms
#   KUBE_SECRET: acr-cdwms-creds  # does not yet exist -- will be created in the same Namespace
#   SYNC_PERIOD: "3600"           # ACR tokens expire every 3 hours; refresh faster than that
# ---
# apiVersion: aadpodidentity.k8s.io/v1
# kind: AzureIdentity
# metadata:
#   name: credentials-sync
#   namespace: flux-system
# spec:
#   clientID: e107f01d-522e-49ac-9925-f47c27e35b4c
#   resourceID: /subscriptions/b9c770d1-cde9-4da3-ae40-95ce1a4fac0c/resourcegroups/cdw-kubernetes-20210302/providers/Microsoft.ManagedIdentity/userAssignedIdentities/acr-sync
#   type: 0  # user-managed identity