---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  releaseName: redis
  targetNamespace: redis-system
  interval: 10m0s
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis
      version: 12.1.1
  values:
    usePassword: false
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: false
